# Dockerfile for Jupyter Lab Deployment

FROM python:3

RUN  apt-get update && apt-get install -y curl

COPY ./app/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY ./rampserv /rampserv

# TODO: Currently only works with root user
USER root
WORKDIR /

RUN pip install jupyterlab
RUN pip install rampserv/

WORKDIR /home/mount