apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyter
  labels:
    service: jupyter
    release: {{ .Release.Name }}
spec:
  selector:
    app: jupyter
    release: {{ .Release.Name }}
  ports:
  - port: 8000
    targetPort: 8888
