apiVersion: v1
kind: Service
metadata:
  name: reload
  labels:
    service: reload
    release: {{ .Release.Name }}
spec:
  selector:
    app: serverless
    release: {{ .Release.Name }}
  ports:
  - port: 80
    targetPort: 80
