apiVersion: v1
kind: Secret
metadata:
  name: stagingsecret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-3"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.imagePullSecret }}
